// Code generated by "stringer -type=MarketSignal"; DO NOT EDIT.

package econerra

import "strconv"

const _MarketSignal_name = "SignalWeakSignalFairSignalStrong"

var _MarketSignal_index = [...]uint8{0, 10, 20, 32}

func (i MarketSignal) String() string {
	if i >= MarketSignal(len(_MarketSignal_index)-1) {
		return "MarketSignal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MarketSignal_name[_MarketSignal_index[i]:_MarketSignal_index[i+1]]
}
