// Code generated by "stringer -type=Side"; DO NOT EDIT.

package econerra

import "strconv"

const _Side_name = "BuySell"

var _Side_index = [...]uint8{0, 3, 7}

func (i Side) String() string {
	if i >= Side(len(_Side_index)-1) {
		return "Side(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Side_name[_Side_index[i]:_Side_index[i+1]]
}
